# Generated by Django 2.2.4 on 2023-10-08 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_dcxa_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nominee',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nominee_relation',
        ),
    ]
