stages:
  - build

build:
  image: python:3.10
  stage: build
  script:
    - apt-get update -qy
    - apt-get install -y python-dev-is-python3 python3-pip
    - pip install . pytest-runner pycodestyle
    - python setup.py pytest
    - pycodestyle --max-line-length=120 lib
