# Generated by Django 2.2.4 on 2023-09-25 01:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0012_auto_20210722_0137'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTotal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=25, null=True)),
                ('active', models.BooleanField()),
                ('left_months', models.IntegerField()),
                ('direct', models.CharField(blank=True, max_length=25, null=True)),
                ('business', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='level.LevelIncomeSettings')),
            ],
        ),
    ]
