# Generated by Django 2.2.2 on 2021-07-22 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoCurrencyPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('crypto', models.CharField(max_length=50)),
                ('crypto_code', models.CharField(max_length=15, null=True)),
                ('address', models.CharField(max_length=200)),
                ('address_reused', models.BooleanField(default=False)),
                ('tx_hash', models.CharField(help_text='Transaction ID', max_length=150, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('processing', 'Processing')], default='new', max_length=50)),
                ('crypto_amount', models.DecimalField(decimal_places=12, help_text='Calculated crypto amount for fiat', max_digits=17)),
                ('paid_crypto_amount', models.DecimalField(decimal_places=12, default=0, help_text='Paid crypto amount', max_digits=17, null=True)),
                ('fiat_amount', models.DecimalField(decimal_places=2, help_text='Fiat amount', max_digits=9)),
                ('fiat_currency', models.CharField(default='USD', max_length=5)),
                ('payment_title', models.CharField(max_length=100, null=True)),
                ('payment_description', models.CharField(max_length=250, null=True)),
                ('object_id', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child_payment', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent', to='cryptopay.CryptoCurrencyPayment')),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('parent_payment', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='cryptopay.CryptoCurrencyPayment')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crypto_payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
